### ISSUE TITLE
Checkpoint is not available

### ISSUE THREAD

**Issue by shlyahin** [semchan/NLUT#1]
Hello, unfortunatelly you pre-trained checkpoint https://pan.baidu.com/s/1YgepbC62QKwyZDfOLUHMlg is not available now.

**Comment by yahskapar** [comment]
I was able to successfully download the pre-trained checkpoint about a week ago, but yeah, looks like it's not available now for whatever reason. If you want, email me at akshay@cs.unc.edu and I can try to share the pre-trained checkpoint with you somehow (hopefully this is ok with the authors given the circumstances).

**Comment by semchan** [comment]
> Hello, unfortunatelly you pre-trained checkpoint https://pan.baidu.com/s/1YgepbC62QKwyZDfOLUHMlg is not available now.

Sorry for that. I have updated the new share for you in the below link: https://pan.baidu.com/s/1VddHbq2cBy5RcKOp8S5eSg 
code：1234 . thanks

**Comment by shlyahin** [comment]
> > Hello, unfortunatelly you pre-trained checkpoint https://pan.baidu.com/s/1YgepbC62QKwyZDfOLUHMlg is not available now.
> 
> Sorry for that. I have updated the new share for you in the below link: https://pan.baidu.com/s/1VddHbq2cBy5RcKOp8S5eSg code：1234 . thanks

Thank you!
