### ISSUE TITLE
image or video data

### ISSUE THREAD

**Issue by zhaoyue99** [semchan/NLUT#10]
Hello, could you please provide some test data of images or videos presented in your paper? Thank you very much!

**Comment by semchan** [comment]
> Hello, could you please provide some test data of images or videos presented in your paper? Thank you very much!

sure. You can check from here: https://github.com/semchan/NLUT/tree/main/data

**Comment by zhaoyue99** [comment]
> > Hello, could you please provide some test data of images or videos presented in your paper? Thank you very much!
> 
> sure. You can check from here: https://github.com/semchan/NLUT/tree/main/data

That's great! Thank you for your reply.
