### ISSUE TITLE
Probem with trilinear building

### ISSUE THREAD

**Issue by shlyahin** [semchan/NLUT#3]
When I try to build trilinear module, I catch the next error:

> RuntimeError: 
> The detected CUDA version (11.8) mismatches the version that was used to compile
> PyTorch (10.2). Please make sure to use the same CUDA versions.

I am running next  lines in Colab notebook:
```
!git clone https://github.com/semchan/NLUT
!pip install -r /content/NLUT/requirements.txt
%cd /content/NLUT/trilinear_cpp
!sh setup.sh

```
**Full trace:**

> Including CUDA code.
> running install
> running bdist_egg
> running egg_info
> writing trilinear.egg-info/PKG-INFO
> writing dependency_links to trilinear.egg-info/dependency_links.txt
> writing top-level names to trilinear.egg-info/top_level.txt
> /usr/local/lib/python3.9/dist-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
>   warnings.warn(msg.format('we could not find ninja.'))
> reading manifest file 'trilinear.egg-info/SOURCES.txt'
> writing manifest file 'trilinear.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_ext
> Traceback (most recent call last):
>   File "/content/NLUT/trilinear_cpp/setup.py", line 7, in <module>
>     setup(
>   File "/usr/local/lib/python3.9/dist-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py", line 67, in run
>     self.do_egg_install()
>   File "/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
>     self.run_command('bdist_egg')
>   File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.9/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/usr/local/lib/python3.9/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
>     self.run_command(cmdname)
>   File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.9/dist-packages/setuptools/command/install_lib.py", line 11, in run
>     self.build()
>   File "/usr/lib/python3.9/distutils/command/install_lib.py", line 109, in build
>     self.run_command('build_ext')
>   File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.9/dist-packages/setuptools/command/build_ext.py", line 79, in run
>     _build_ext.run(self)
>   File "/usr/local/lib/python3.9/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
>     _build_ext.build_ext.run(self)
>   File "/usr/lib/python3.9/distutils/command/build_ext.py", line 340, in run
>     self.build_extensions()
>   File "/usr/local/lib/python3.9/dist-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
>     self._check_cuda_version()
>   File "/usr/local/lib/python3.9/dist-packages/torch/utils/cpp_extension.py", line 781, in _check_cuda_version
>     raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
> RuntimeError: 
> The detected CUDA version (11.8) mismatches the version that was used to compile
> PyTorch (10.2). Please make sure to use the same CUDA versions.

**Comment by yahskapar** [comment]
Hi @shlyahin,

I also ran into this problem, albeit in my case it was with a different detected version (11.0). I resolved this using the below PyTorch install command from [here](https://pytorch.org/get-started/previous-versions/):

```
pip3 install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/cu111/torch_stable.html
```

This maintains the torch version of 1.10.1 (also specified in this repo's `requirements.txt` file) while bumping the compiled CUDA version to 11.1. I think this may work in your case since all you might need to do is bump up the compiled CUDA version from 10.x to 11.x, but in case it doesn't work you can also try other versions [here](https://pytorch.org/get-started/previous-versions/) or the below command with CUDA 11.8:

```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

**Comment by shlyahin** [comment]
Hello @yahskapar ,

Thank you. This works for me. Now I have trilinear builded.

But error with checkpoint occures when I run inference_finetuning_image.py script:
RuntimeError: Error(s) in loading state_dict for NLUTNet:
	Unexpected key(s) in state_dict: "blurer.op.1.weight", "SB1.conv1.conv2d.weight", "SB1.conv1.conv2d.bias", "SB1.conv1.bn.weight", "SB1.conv1.bn.bias", "SB1.conv1.bn.running_mean", "SB1.conv1.bn.running_var", "SB1.conv1.bn.num_batches_tracked", "SB1.conv2.conv2d.weight", "SB1.conv2.conv2d.bias", "SB1.conv2.bn.weight", "SB1.conv2.bn.bias", "SB1.conv2.bn.running_mean", "SB1.conv2.bn.running_var", "SB1.conv2.bn.num_batches_tracked". 
	
Full trace:

> now device is cuda:0
> n=2048 s=32 w=32 ++
> Total params: 22.01M
> --------loading checkpoint----------
> => loading checkpoint './336999_style_lut.pth'
> Traceback (most recent call last):
>   File "/content/NLUT/inference_finetuning_image.py", line 230, in <module>
>     lut = finetuning_train(opt, original, example)
>   File "/content/NLUT/inference_finetuning_image.py", line 86, in finetuning_train
>     model.load_state_dict(checkpoint['state_dict'])
>   File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for NLUTNet:
> 	Unexpected key(s) in state_dict: "blurer.op.1.weight", "SB1.conv1.conv2d.weight", "SB1.conv1.conv2d.bias", "SB1.conv1.bn.weight", "SB1.conv1.bn.bias", "SB1.conv1.bn.running_mean", "SB1.conv1.bn.running_var", "SB1.conv1.bn.num_batches_tracked", "SB1.conv2.conv2d.weight", "SB1.conv2.conv2d.bias", "SB1.conv2.bn.weight", "SB1.conv2.bn.bias", "SB1.conv2.bn.running_mean", "SB1.conv2.bn.running_var", "SB1.conv2.bn.num_batches_tracked".

**Comment by yahskapar** [comment]
I also had this issue, try changing line 86 (as reported in your traceback) to:

```
model.load_state_dict(checkpoint['state_dict'], strict=False)
```

That should prevent that error when loading the pre-trained model.

**Comment by shlyahin** [comment]
@yahskapar Thanks. Now script works.

**Comment by jiangtguo** [comment]
@shlyahin I have also encountered the same problem. How did you solve it?
