### ISSUE TITLE
problem with checkpoint

### ISSUE THREAD

**Issue by videoprice** [semchan/NLUT#5]
Hi, have this problem

now device is cuda:0
n=2048 s=32 w=32 ++
Total params: 22.01M
--------loading checkpoint----------
=> loading checkpoint '336999_style_lut.pth'
Traceback (most recent call last):
  File "W:\NLUT\inference_finetuning_video.py", line 377, in <module>
    finetuning_train(opt, original, example)
  File "W:\NLUT\inference_finetuning_video.py", line 156, in finetuning_train
    model.load_state_dict(checkpoint['state_dict'])
  File "C:\ProgramData\Anaconda3\envs\NLUT-styles\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NLUTNet:
        Unexpected key(s) in state_dict: "blurer.op.1.weight", "SB1.conv1.conv2d.weight", "SB1.conv1.conv2d.bias", "SB1.conv1.bn.weight", "SB1.conv1.bn.bias", "SB1.conv1.bn.running_mean", "SB1.conv1.bn.running_var", "SB1.conv1.bn.num_batches_tracked", "SB1.conv2.conv2d.weight", "SB1.conv2.conv2d.bias", "SB1.conv2.bn.weight", "SB1.conv2.bn.bias", "SB1.conv2.bn.running_mean", "SB1.conv2.bn.running_var", "SB1.conv2.bn.num_batches_tracked".

**Comment by sleimanitani** [comment]
Hi, how did you solve this issue?
